# Generated by Django 5.2 on 2026-02-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lliga',
            options={'verbose_name_plural': 'Lligues'},
        ),
        migrations.AddField(
            model_name='jugador',
            name='edat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='cognom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lliga',
            name='pais',
            field=models.CharField(default='Catalunya', max_length=50),
        ),
        migrations.AlterField(
            model_name='partit',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
